INSERT INTO `question` (`title`, `content`, `tags`, `answer`, `difficulty`, `judgeCase`, `judgeConfig`, `userId`) VALUES
('合并区间', '给出一个区间的集合，请合并所有重叠的区间。\n\n示例 1:\n输入: intervals = [[1,3],[2,6],[8,10],[15,18]]\n输出: [[1,6],[8,10],[15,18]]\n解释: 区间 [1,3] 和 [2,6] 重叠, 将它们合并为 [1,6].', '["数组","排序"]', 'public int[][] merge(int[][] intervals) {\n    Arrays.sort(intervals, (v1, v2) -> v1[0] - v2[0]);\n    int[][] res = new int[intervals.length][2];\n    int idx = -1;\n    for (int[] interval: intervals) {\n        if (idx == -1 || interval[0] > res[idx][1]) {\n            res[++idx] = interval;\n        } else {\n            res[idx][1] = Math.max(res[idx][1], interval[1]);\n        }\n    }\n    return Arrays.copyOf(res, idx + 1);\n}', 'medium', '[{"input":"[[1,3],[2,6],[8,10],[15,18]]","output":"[[1,6],[8,10],[15,18]]"},{"input":"[[1,4],[4,5]]","output":"[[1,5]]"}]', '{"timeLimit":1000,"memoryLimit":256,"stackLimit":256}', 1),

('最长公共子序列', '给定两个字符串 text1 和 text2，返回这两个字符串的最长公共子序列的长度。\n\n示例 1:\n输入：text1 = "abcde", text2 = "ace" \n输出：3  \n解释：最长公共子序列是 "ace"，它的长度为 3。', '["动态规划","字符串"]', 'public int longestCommonSubsequence(String text1, String text2) {\n    int m = text1.length(), n = text2.length();\n    int[][] dp = new int[m + 1][n + 1];\n    for (int i = 1; i <= m; i++) {\n        for (int j = 1; j <= n; j++) {\n            if (text1.charAt(i-1) == text2.charAt(j-1)) {\n                dp[i][j] = dp[i-1][j-1] + 1;\n            } else {\n                dp[i][j] = Math.max(dp[i-1][j], dp[i][j-1]);\n            }\n        }\n    }\n    return dp[m][n];\n}', 'medium', '[{"input":"\"abcde\",\"ace\"","output":"3"},{"input":"\"abc\",\"abc\"","output":"3"}]', '{"timeLimit":1000,"memoryLimit":256,"stackLimit":256}', 1),

('打家劫舍', '你是一个专业的小偷，计划偷窃沿街的房屋。每间房内都藏有一定的现金，影响你偷窃的唯一制约因素就是相邻的房屋装有相互连通的防盗系统，如果两间相邻的房屋在同一晚上被小偷闯入，系统会自动报警。\n\n给定一个代表每个房屋存放金额的非负整数数组，计算你不触动警报装置的情况下，一夜之内能够偷窃到的最高金额。', '["动态规划"]', 'public int rob(int[] nums) {\n    if (nums == null || nums.length == 0) {\n        return 0;\n    }\n    if (nums.length == 1) {\n        return nums[0];\n    }\n    int[] dp = new int[nums.length];\n    dp[0] = nums[0];\n    dp[1] = Math.max(nums[0], nums[1]);\n    for (int i = 2; i < nums.length; i++) {\n        dp[i] = Math.max(dp[i-1], dp[i-2] + nums[i]);\n    }\n    return dp[nums.length-1];\n}', 'medium', '[{"input":"[1,2,3,1]","output":"4"},{"input":"[2,7,9,3,1]","output":"12"}]', '{"timeLimit":1000,"memoryLimit":256,"stackLimit":256}', 1),

('最小路径和', '给定一个包含非负整数的 m x n 网格，请找出一条从左上角到右下角的路径，使得路径上的数字总和为最小。\n\n说明：每次只能向下或者向右移动一步。', '["动态规划","数组"]', 'public int minPathSum(int[][] grid) {\n    int m = grid.length;\n    int n = grid[0].length;\n    int[][] dp = new int[m][n];\n    dp[0][0] = grid[0][0];\n    for(int i = 1; i < m; i++) {\n        dp[i][0] = dp[i-1][0] + grid[i][0];\n    }\n    for(int j = 1; j < n; j++) {\n        dp[0][j] = dp[0][j-1] + grid[0][j];\n    }\n    for(int i = 1; i < m; i++) {\n        for(int j = 1; j < n; j++) {\n            dp[i][j] = Math.min(dp[i-1][j], dp[i][j-1]) + grid[i][j];\n        }\n    }\n    return dp[m-1][n-1];\n}', 'medium', '[{"input":"[[1,3,1],[1,5,1],[4,2,1]]","output":"7"}]', '{"timeLimit":1000,"memoryLimit":256,"stackLimit":256}', 1),

('最长回文子串', '给定一个字符串 s，找到 s 中最长的回文子串。你可以假设 s 的最大长度为 1000。', '["字符串","动态规划"]', 'public String longestPalindrome(String s) {\n    if (s == null || s.length() < 2) {\n        return s;\n    }\n    int start = 0, end = 0;\n    for (int i = 0; i < s.length(); i++) {\n        int len1 = expandAroundCenter(s, i, i);\n        int len2 = expandAroundCenter(s, i, i + 1);\n        int len = Math.max(len1, len2);\n        if (len > end - start) {\n            start = i - (len - 1) / 2;\n            end = i + len / 2;\n        }\n    }\n    return s.substring(start, end + 1);\n}\n\nprivate int expandAroundCenter(String s, int left, int right) {\n    while (left >= 0 && right < s.length() && s.charAt(left) == s.charAt(right)) {\n        left--;\n        right++;\n    }\n    return right - left - 1;\n}', 'medium', '[{"input":"\"babad\"","output":"\"bab\""},{"input":"\"cbbd\"","output":"\"bb\""}]', '{"timeLimit":1000,"memoryLimit":256,"stackLimit":256}', 1),

('最大子数组和', '给定一个整数数组 nums ，找到一个具有最大和的连续子数组（子数组最少包含一个元素），返回其最大和。', '["数组","动态规划","分治"]', 'public int maxSubArray(int[] nums) {\n    int maxSum = nums[0];\n    int currentSum = nums[0];\n    for (int i = 1; i < nums.length; i++) {\n        currentSum = Math.max(nums[i], currentSum + nums[i]);\n        maxSum = Math.max(maxSum, currentSum);\n    }\n    return maxSum;\n}', 'easy', '[{"input":"[-2,1,-3,4,-1,2,1,-5,4]","output":"6"},{"input":"[1]","output":"1"}]', '{"timeLimit":1000,"memoryLimit":256,"stackLimit":256}', 1),

('二叉树的层序遍历', '给你一个二叉树，请你返回其按 层序遍历 得到的节点值。 （即逐层地，从左到右访问所有节点）。', '["树","广度优先搜索"]', 'public List<List<Integer>> levelOrder(TreeNode root) {\n    List<List<Integer>> result = new ArrayList<>();\n    if (root == null) {\n        return result;\n    }\n    Queue<TreeNode> queue = new LinkedList<>();\n    queue.offer(root);\n    while (!queue.isEmpty()) {\n        int size = queue.size();\n        List<Integer> level = new ArrayList<>();\n        for (int i = 0; i < size; i++) {\n            TreeNode node = queue.poll();\n            level.add(node.val);\n            if (node.left != null) {\n                queue.offer(node.left);\n            }\n            if (node.right != null) {\n                queue.offer(node.right);\n            }\n        }\n        result.add(level);\n    }\n    return result;\n}', 'medium', '[{"input":"[3,9,20,null,null,15,7]","output":"[[3],[9,20],[15,7]]"}]', '{"timeLimit":1000,"memoryLimit":256,"stackLimit":256}', 1),

('有效的括号', '给定一个只包括 \'(\', \')\', \'{\', \'}\', \'[\', \']\' 的字符串，判断字符串是否有效。\n\n有效字符串需满足：\n1. 左括号必须用相同类型的右括号闭合。\n2. 左括号必须以正确的顺序闭合。\n\n注意空字符串可被认为是有效字符串。', '["栈","字符串"]', 'public boolean isValid(String s) {\n    Stack<Character> stack = new Stack<>();\n    for (char c : s.toCharArray()) {\n        if (c == \'(\') {\n            stack.push(\')\');\n        } else if (c == \'{\') {\n            stack.push(\'}\');\n        } else if (c == \'[\') {\n            stack.push(\']\');\n        } else if (stack.isEmpty() || stack.pop() != c) {\n            return false;\n        }\n    }\n    return stack.isEmpty();\n}', 'easy', '[{"input":"\"()\"\n","output":"true"},{"input":"\"()[]{}\"\n","output":"true"},{"input":"\"(]\"\n","output":"false"}]', '{"timeLimit":1000,"memoryLimit":256,"stackLimit":256}', 1),

('最长递增子序列', '给你一个整数数组 nums ，找到其中最长严格递增子序列的长度。\n\n子序列是由数组派生而来的序列，删除（或不删除）数组中的元素而不改变其余元素的顺序。例如，[3,6,2,7] 是数组 [0,3,1,6,2,2,7] 的子序列。', '["数组","二分查找","动态规划"]', 'public int lengthOfLIS(int[] nums) {\n    int[] dp = new int[nums.length];\n    int len = 0;\n    for (int num : nums) {\n        int i = Arrays.binarySearch(dp, 0, len, num);\n        if (i < 0) {\n            i = -(i + 1);\n        }\n        dp[i] = num;\n        if (i == len) {\n            len++;\n        }\n    }\n    return len;\n}', 'medium', '[{"input":"[10,9,2,5,3,7,101,18]","output":"4"},{"input":"[0,1,0,3,2,3]","output":"4"}]', '{"timeLimit":1000,"memoryLimit":256,"stackLimit":256}', 1),

('单词搜索', '给定一个二维网格和一个单词，找出该单词是否存在于网格中。\n\n单词必须按照字母顺序，通过相邻的单元格内的字母构成，其中"相邻"单元格是那些水平相邻或垂直相邻的单元格。同一个单元格内的字母不允许被重复使用。', '["数组","回溯","深度优先搜索"]', 'public boolean exist(char[][] board, String word) {\n    for(int i = 0; i < board.length; i++) {\n        for(int j = 0; j < board[0].length; j++) {\n            if(dfs(board, i, j, word, 0)) return true;\n        }\n    }\n    return false;\n}\n\nprivate boolean dfs(char[][] board, int i, int j, String word, int k) {\n    if(k == word.length()) return true;\n    if(i < 0 || j < 0 || i >= board.length || j >= board[0].length || board[i][j] != word.charAt(k)) return false;\n    char temp = board[i][j];\n    board[i][j] = \'/\';\n    boolean result = dfs(board, i+1, j, word, k+1) || dfs(board, i-1, j, word, k+1) || \n                     dfs(board, i, j+1, word, k+1) || dfs(board, i, j-1, word, k+1);\n    board[i][j] = temp;\n    return result;\n}', 'medium', '[{"input":"[[\"A\",\"B\",\"C\",\"E\"],[\"S\",\"F\",\"C\",\"S\"],[\"A\",\"D\",\"E\",\"E\"]],\"ABCCED\"","output":"true"}]', '{"timeLimit":1000,"memoryLimit":256,"stackLimit":256}', 1);