INSERT INTO `question` (`title`, `content`, `tags`, `answer`, `difficulty`, `judgeCase`, `judgeConfig`, `userId`) VALUES
('搜索旋转排序数组', '整数数组 nums 按升序排列，数组中的值 互不相同 。\n\n在传递给函数之前，nums 在预先未知的某个下标 k（0 <= k < nums.length）上进行了 旋转，使数组变为 [nums[k], nums[k+1], ..., nums[n-1], nums[0], nums[1], ..., nums[k-1]]（下标 从 0 开始 计数）。\n\n给你 旋转后 的数组 nums 和一个整数 target ，如果 nums 中存在这个目标值 target ，则返回它的下标，否则返回 -1 。', '["数组","二分查找"]', 'public int search(int[] nums, int target) {\n    int left = 0, right = nums.length - 1;\n    while (left <= right) {\n        int mid = left + (right - left) / 2;\n        if (nums[mid] == target) {\n            return mid;\n        }\n        if (nums[left] <= nums[mid]) {\n            if (target >= nums[left] && target < nums[mid]) {\n                right = mid - 1;\n            } else {\n                left = mid + 1;\n            }\n        } else {\n            if (target > nums[mid] && target <= nums[right]) {\n                left = mid + 1;\n            } else {\n                right = mid - 1;\n            }\n        }\n    }\n    return -1;\n}', 'medium', '[{"input":"[4,5,6,7,0,1,2],0","output":"4"},{"input":"[4,5,6,7,0,1,2],3","output":"-1"}]', '{"timeLimit":1000,"memoryLimit":256,"stackLimit":256}', 1),

('组合总和', '给定一个无重复元素的数组 candidates 和一个目标数 target ，找出 candidates 中所有可以使数字和为 target 的组合。\n\ncandidates 中的数字可以无限制重复被选取。', '["数组","回溯"]', 'public List<List<Integer>> combinationSum(int[] candidates, int target) {\n    List<List<Integer>> result = new ArrayList<>();\n    backtrack(result, new ArrayList<>(), candidates, target, 0);\n    return result;\n}\n\nprivate void backtrack(List<List<Integer>> result, List<Integer> temp, int[] candidates, int remain, int start) {\n    if (remain < 0) return;\n    if (remain == 0) {\n        result.add(new ArrayList<>(temp));\n        return;\n    }\n    for (int i = start; i < candidates.length; i++) {\n        temp.add(candidates[i]);\n        backtrack(result, temp, candidates, remain - candidates[i], i);\n        temp.remove(temp.size() - 1);\n    }\n}', 'medium', '[{"input":"[2,3,6,7],7","output":"[[2,2,3],[7]]"},{"input":"[2,3,5],8","output":"[[2,2,2,2],[2,3,3],[3,5]]"}]', '{"timeLimit":1000,"memoryLimit":256,"stackLimit":256}', 1),

('跳跃游戏', '给定一个非负整数数组 nums ，你最初位于数组的 第一个下标 。\n\n数组中的每个元素代表你在该位置可以跳跃的最大长度。\n\n判断你是否能够到达最后一个下标。', '["贪心","数组"]', 'public boolean canJump(int[] nums) {\n    int maxReach = 0;\n    for (int i = 0; i <= maxReach && i < nums.length; i++) {\n        maxReach = Math.max(maxReach, i + nums[i]);\n    }\n    return maxReach >= nums.length - 1;\n}', 'medium', '[{"input":"[2,3,1,1,4]","output":"true"},{"input":"[3,2,1,0,4]","output":"false"}]', '{"timeLimit":1000,"memoryLimit":256,"stackLimit":256}', 1),

('最小栈', '设计一个支持 push ，pop ，top 操作，并能在常数时间内检索到最小元素的栈。\n\n实现 MinStack 类:\n\nMinStack() 初始化堆栈对象。\nvoid push(int val) 将元素val推入堆栈。\nvoid pop() 删除堆栈顶部的元素。\nint top() 获取堆栈顶部的元素。\nint getMin() 获取堆栈中的最小元素。', '["栈","设计"]', 'class MinStack {\n    private Stack<Integer> stack;\n    private Stack<Integer> minStack;\n\n    public MinStack() {\n        stack = new Stack<>();\n        minStack = new Stack<>();\n    }\n    \n    public void push(int val) {\n        stack.push(val);\n        if (minStack.isEmpty() || val <= minStack.peek()) {\n            minStack.push(val);\n        }\n    }\n    \n    public void pop() {\n        if (stack.pop().equals(minStack.peek())) {\n            minStack.pop();\n        }\n    }\n    \n    public int top() {\n        return stack.peek();\n    }\n    \n    public int getMin() {\n        return minStack.peek();\n    }\n}', 'easy', '[{"input":"[\"MinStack\",\"push\",\"push\",\"push\",\"getMin\",\"pop\",\"top\",\"getMin\"]","output":"[null,null,null,null,-3,null,0,-2]"},{"input":"[[],[2147483646],[2147483646],[2147483647]]","output":"[null,null,null,null]"}]', '{"timeLimit":1000,"memoryLimit":256,"stackLimit":256}', 1),

('二叉树的最近公共祖先', '给定一个二叉树, 找到该树中两个指定节点的最近公共祖先。\n\n百度百科中最近公共祖先的定义为："对于有根树 T 的两个节点 p、q，最近公共祖先表示为一个节点 x，满足 x 是 p、q 的祖先且 x 的深度尽可能大（一个节点也可以是它自己的祖先）。"', '["树","深度优先搜索"]', 'public TreeNode lowestCommonAncestor(TreeNode root, TreeNode p, TreeNode q) {\n    if (root == null || root == p || root == q) {\n        return root;\n    }\n    TreeNode left = lowestCommonAncestor(root.left, p, q);\n    TreeNode right = lowestCommonAncestor(root.right, p, q);\n    if (left == null) {\n        return right;\n    }\n    if (right == null) {\n        return left;\n    }\n    return root;\n}', 'medium', '[{"input":"[3,5,1,6,2,0,8,null,null,7,4],5,1","output":"3"},{"input":"[3,5,1,6,2,0,8,null,null,7,4],5,4","output":"5"}]', '{"timeLimit":1000,"memoryLimit":256,"stackLimit":256}', 1);