-- 代码相似度记录表
CREATE TABLE IF NOT EXISTS `code_similarity` (
    `id` BIGINT NOT NULL COMMENT '主键ID',
    `question_id` BIGINT NOT NULL COMMENT '题目ID',
    `submit_id1` BIGINT NOT NULL COMMENT '提交记录1 ID',
    `user_id1` BIGINT NOT NULL COMMENT '提交记录1 用户ID',
    `submit_id2` BIGINT NOT NULL COMMENT '提交记录2 ID',
    `user_id2` BIGINT NOT NULL COMMENT '提交记录2 用户ID',
    `similarity_score` INT NOT NULL COMMENT '相似度分数(0-100)',
    `similarity_level` VARCHAR(20) NOT NULL COMMENT '相似度等级(HIGH/MEDIUM/LOW)',
    `similar_lines` INT DEFAULT 0 COMMENT '相似行数',
    `total_lines` INT DEFAULT 0 COMMENT '总行数',
    `similar_fragments` TEXT COMMENT '相似代码片段(JSON格式)',
    `algorithm_type` VARCHAR(50) DEFAULT 'LCS' COMMENT '检测算法类型',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `create_user` BIGINT COMMENT '创建人',
    `is_processed` TINYINT DEFAULT 0 COMMENT '是否已处理(0-未处理,1-已处理)',
    `process_result` VARCHAR(255) COMMENT '处理结果',
    PRIMARY KEY (`id`),
    KEY `idx_question_id` (`question_id`),
    KEY `idx_user_id1` (`user_id1`),
    KEY `idx_user_id2` (`user_id2`),
    KEY `idx_similarity_score` (`similarity_score`),
    KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='代码相似度记录表';

-- 错题本表
CREATE TABLE IF NOT EXISTS `mistake_notebook` (
    `id` BIGINT NOT NULL COMMENT '主键ID',
    `user_id` BIGINT NOT NULL COMMENT '用户ID',
    `question_id` BIGINT NOT NULL COMMENT '题目ID',
    `submit_id` BIGINT COMMENT '提交记录ID',
    `mistake_type` VARCHAR(50) NOT NULL COMMENT '错误类型(COMPILE_ERROR, RUNTIME_ERROR, WRONG_ANSWER, TIME_LIMIT_EXCEEDED)',
    `error_message` TEXT COMMENT '错误信息',
    `user_code` TEXT COMMENT '用户提交的代码',
    `notes` TEXT COMMENT '用户笔记',
    `category` VARCHAR(100) COMMENT '错题分类',
    `is_reviewed` TINYINT DEFAULT 0 COMMENT '是否已复习(0-未复习,1-已复习)',
    `review_count` INT DEFAULT 0 COMMENT '复习次数',
    `last_review_time` DATETIME COMMENT '最后复习时间',
    `remind_time` DATETIME COMMENT '提醒复习时间',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `is_delete` TINYINT DEFAULT 0 COMMENT '是否删除(0-未删除,1-已删除)',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_user_question` (`user_id`, `question_id`),
    KEY `idx_user_id` (`user_id`),
    KEY `idx_question_id` (`question_id`),
    KEY `idx_mistake_type` (`mistake_type`),
    KEY `idx_is_reviewed` (`is_reviewed`),
    KEY `idx_remind_time` (`remind_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='错题本表';

-- 学习报告表
CREATE TABLE IF NOT EXISTS `learning_report` (
    `id` BIGINT NOT NULL COMMENT '主键ID',
    `user_id` BIGINT NOT NULL COMMENT '用户ID',
    `report_type` VARCHAR(50) NOT NULL COMMENT '报告类型(DAILY, WEEKLY, MONTHLY, CUSTOM)',
    `start_date` DATE NOT NULL COMMENT '开始日期',
    `end_date` DATE NOT NULL COMMENT '结束日期',
    `total_submits` INT DEFAULT 0 COMMENT '总提交次数',
    `passed_questions` INT DEFAULT 0 COMMENT '通过题目数',
    `accuracy_rate` DECIMAL(5,2) DEFAULT 0.00 COMMENT '正确率',
    `study_time` INT DEFAULT 0 COMMENT '学习时长(分钟)',
    `knowledge_points` TEXT COMMENT '掌握知识点(JSON格式)',
    `weak_points` TEXT COMMENT '薄弱知识点(JSON格式)',
    `score_distribution` TEXT COMMENT '得分分布(JSON格式)',
    `language_preference` TEXT COMMENT '编程语言偏好(JSON格式)',
    `summary` TEXT COMMENT '学习总结',
    `suggestions` TEXT COMMENT '学习建议',
    `report_data` TEXT COMMENT '完整报告数据(JSON格式)',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_user_id` (`user_id`),
    KEY `idx_report_type` (`report_type`),
    KEY `idx_start_date` (`start_date`),
    KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='学习报告表';

-- 许可证管理表
CREATE TABLE IF NOT EXISTS `license` (
    `id` BIGINT NOT NULL COMMENT '主键ID',
    `license_key` VARCHAR(255) NOT NULL COMMENT '许可证密钥',
    `license_type` VARCHAR(50) NOT NULL COMMENT '许可证类型(TRIAL, STANDARD, PREMIUM, ENTERPRISE)',
    `school_name` VARCHAR(255) COMMENT '学校/机构名称',
    `contact_person` VARCHAR(100) COMMENT '联系人',
    `contact_email` VARCHAR(255) COMMENT '联系邮箱',
    `contact_phone` VARCHAR(50) COMMENT '联系电话',
    `max_users` INT DEFAULT 100 COMMENT '最大用户数',
    `current_users` INT DEFAULT 0 COMMENT '当前用户数',
    `max_questions` INT DEFAULT 1000 COMMENT '最大题目数',
    `enable_contest` TINYINT DEFAULT 1 COMMENT '是否启用比赛功能',
    `enable_plagiarism` TINYINT DEFAULT 1 COMMENT '是否启用查重功能',
    `features` TEXT COMMENT '启用的功能列表(JSON格式)',
    `start_date` DATE NOT NULL COMMENT '生效日期',
    `end_date` DATE NOT NULL COMMENT '到期日期',
    `is_active` TINYINT DEFAULT 1 COMMENT '是否激活(0-未激活,1-已激活,2-已过期)',
    `activation_time` DATETIME COMMENT '激活时间',
    `last_check_time` DATETIME COMMENT '最后检查时间',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_license_key` (`license_key`),
    KEY `idx_is_active` (`is_active`),
    KEY `idx_end_date` (`end_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='许可证管理表';
